project-setup
BukolaF/loan_website pull request #2
Opened 2024-01-16 17:21 UTC by BukolaF

This Pr,
-includes the addition of a gitignore file
-deletion of files that should not be pushed to repo
-includes changes made to the navbar component to modify the logo

2024-01-16 21:21 UTC, BalogunDell requested changes

2024-01-16 21:21 UTC, BalogunDell commented on README copy.md
> +This section has moved here: [https://facebook.github.io/create-react-app/docs/troubleshooting#npm-run-build-fails-to-minify](https://facebook.github.io/create-react-app/docs/troubleshooting#npm-run-
@BukolaF Why did we delete the original readMe and now we have a copy?

2024-01-16 21:21 UTC, BalogunDell commented on src/components/Navbar.jsx
> +  const [nav, setNav] = useState(false);
This is a boolean, please use a descriptive name with `is`, `show`,  as the prefix, e.g `showAlert`, `shouldShowAlert`, `isRegistering`

2024-01-16 21:21 UTC, BalogunDell commented on src/components/Navbar.jsx
> +          <li className='p-8'>Contact</li>
Great stuff. but this can be better. 

const links = ['Loans', 'About', 'Login', 'Contact']

```
<ul className='hidden md:flex'>
          <li className='p-8'>loans</li>
          <li className='p-8'>About</li> 
          <li className='p-8'>Login</li>
          <li className='p-8'>Contact</li>
links.map(link =>  <li className='p-8' key={link}>{link}</li>)
</ul>
```

This way you get rid of className code duplication and li code duplication

2024-01-16 21:21 UTC, BalogunDell commented on src/components/Navbar.jsx
> +            <li className='p-8 border-b border-blue-900'>Contact</li>
Same thing here. 

```
 <li className='p-8 border-b border-blue-900'>loans</li>
            <li className='p-8 border-b border-blue-900'>About</li>
            <li className='p-8 border-b border-blue-900'>Login</li>
            <li className='p-8 border-b border-blue-900'>Contact</li>

```
The whole thing can be a component on its own and you can reuse it.

2024-01-17 11:20 UTC, BukolaF commented on README copy.md
> +This section has moved here: [https://facebook.github.io/create-react-app/docs/troubleshooting#npm-run-build-fails-to-minify](https://facebook.github.io/create-react-app/docs/troubleshooting#npm-run-
when i cloned this repository, it saw the existing README file and replaced it @BalogunDell

2024-01-17 11:25 UTC, BalogunDell commented on README copy.md
> +This section has moved here: [https://facebook.github.io/create-react-app/docs/troubleshooting#npm-run-build-fails-to-minify](https://facebook.github.io/create-react-app/docs/troubleshooting#npm-run-
Then let it be renamed. It should not have the copy.

2024-01-17 11:29 UTC, BalogunDell requested changes

2024-01-17 11:29 UTC, BalogunDell commented on src/components/Navbar.jsx
> +          {!showNav ? <AiOutlineClose size={20} /> : <AiOutlineMenu  size={20}/>}
This is valid however for readability, can we use this? 

```{showNav ? <AiOutlineMenu size={20} /> : <AiOutlineClose size={20}/>}```

2024-01-17 11:38 UTC, BukolaF commented on src/components/Navbar.jsx
> +          {!showNav ? <AiOutlineClose size={20} /> : <AiOutlineMenu  size={20}/>}
yeah, we can

2024-01-17 12:04 UTC, BukolaF commented on README copy.md
> +This section has moved here: [https://facebook.github.io/create-react-app/docs/troubleshooting#npm-run-build-fails-to-minify](https://facebook.github.io/create-react-app/docs/troubleshooting#npm-run-
ok. it has been renamed

2024-01-17 12:20 UTC, BalogunDell commented
<img width="1255" alt="Screenshot 2024-01-17 at 7 19 53 AM" src="https://github.com/BukolaF/loan_website/assets/24609423/f3c27c90-79d9-4522-bcd2-9835f604906f">

Please always make your commit clear. It should describe what has been done.

2024-01-17 12:30 UTC, merged