Home-Page-Look
BukolaF/loan_website pull request #3
Opened 2024-01-18 00:56 UTC by BukolaF

This PR:
includes the use of ReactRouter for page routing set in the App.js folder;
shows a home page to display the hero and footer components;
modifies the website header with a new look;
a newly adjusted navbar component for page routing;
includes a page folder in the src folder to accommodate pages

2024-01-18 11:39 UTC, BalogunDell requested changes
Great job so far. I left a few comments.

2024-01-18 11:39 UTC, BalogunDell commented on package.json
> +    "localforage": "^1.10.0",
What's localForage and what's it used for?

2024-01-18 11:39 UTC, BalogunDell commented on package.json
> +    "match-sorter": "^6.3.3",
What's "match-sorter" and what's it used for?

2024-01-18 11:39 UTC, BalogunDell commented on package.json
> +    "sort-by": "^1.2.0",
What's "sort-by" and what's it used for?

2024-01-18 11:39 UTC, BalogunDell commented on src/App.js
> +import  Loans from './pages/Loans';
Please create an index file in pages, and export all of these components from that index file.

That way, you don't have to repeat lines of import for all pages

it becomes

 import {Home, About, Contactm Loans } from './pages';

Same for components
 import {Navbar } from './components';

2024-01-18 11:39 UTC, BalogunDell commented on src/App.js
> +    <div>
Why do we need a div here?

2024-01-18 11:39 UTC, BalogunDell commented on src/App.js
> +        <Route path='/' element={<Navbar />} />
Why are we rendering a component Navbar as the base route? We should be rendering the home

2024-01-18 11:39 UTC, BalogunDell commented on src/App.js
> +        <Route path='Login' element={<Login />} />
Please move all the route Paths to a const file and use them here

e.g 
```
const ROUTE_PATHS = {
about: 'About',
...
}
```
Usage
```
<Route path={ROUTE_PATHS.about} element={<About />} />
```

2024-01-18 11:39 UTC, BalogunDell commented on src/components/Footer.jsx
> +        <div className='mx-w-[1400px] mx-auto grid grid-cols-2 md:grid-cols-4 border-b-2 border-b-blue-950 px-4 py-8'>
`mx-w-[1400px]`, did you mean `max-w-[1400px]` ?

2024-01-18 11:39 UTC, BalogunDell commented on src/components/Footer.jsx
> +               <li className='py-1'>Sign In</li>
This is why I mentioned that you create a reusable component to reuse in your last PR.

Please do it here. 

so it becomes 

<MenuItems items={items}/>

2024-01-18 11:39 UTC, BalogunDell commented on src/components/Footer.jsx
> +                    <li className='py-1'>Testimonials</li>
Same here 

This is why I mentioned that you create a reusable component to reuse in your last PR.

Please do it here. 

so it becomes 

<MenuItems items={items}/>

2024-01-18 11:39 UTC, BalogunDell commented on src/components/Hero.jsx
> +           <Link to='Loans' className=" md:text-lg mx-20 my-20 sm:text-lg text-lg mt-6 hover:bg-gray-700 mt-10 text-lg bg-blue-950 mx-16 px-6 py-6 text-white flex justify-center items-center">Learn m
This will not work, or is it working? 

<Link to='Loans'/> It should take the path value of loans.

2024-01-18 11:39 UTC, BalogunDell commented on src/components/Hero.jsx
> +        <div className='max-w-[800px] mt-[96px] w-full h-screen mx-auto text-center flex flex-col justify-normal'>
Why do you need `justify-normal` here?

2024-01-18 11:39 UTC, BalogunDell commented on src/components/Navbar.jsx
> +    {path: "/About", link: "About"},
This is what <Link to/> expects. 

Also please pay attention to your casing

```
 const navItems =[
    {path: "/loans", link: "Loans"},
    {path: "/about", link: "About"},
```

2024-01-18 11:39 UTC, BalogunDell commented on src/components/Navbar.jsx
> +        <button onClick={handleNav} className='block md:hidden self-center nav-link'>
You don't need to create a function for this. You can simply do 

```
<button onClick={() => setShowNav(!showNav)}
```

and get rid of 

```
const handleNav = () => {
    setShowNav(!showNav)
  }
```

2024-01-19 09:55 UTC, BalogunDell requested changes

2024-01-19 09:55 UTC, BalogunDell commented on src/components/Navbar.jsx
> +    {path: "/about", link: "About"},
Please reuse the ROUTE_PATHS values here

2024-01-19 09:55 UTC, BalogunDell commented on src/components/Footer.jsx
> -               <li className='py-1'>FAQs</li>
Why did we take these out from the footer?

2024-01-19 09:55 UTC, BalogunDell commented on src/components/Hero.jsx
> +           <Link to='loans' className=" md:text-lg mx-20 my-20 sm:text-lg text-lg mt-6 hover:bg-gray-700 mt-10 text-lg bg-blue-950 mx-16 px-6 py-6 text-white flex justify-center items-center">Learn m
<Link to='loans' /> 

Can you make a quick video showing that this works?

2024-01-19 09:55 UTC, BalogunDell commented on src/pages/index.js
> +import About from './About'
Looks like you got this wrong. 

Everything here should be exported for use in other places

import Contact from './Contact'
import Home from './Home'
import Loans from './Loans'
import Login from './Login'

1. You have to change from default export to named export in all these components
2. You have to export everything from each component here. 
3. You have to import them all from one place anywhere you are using them


1. Named export = `export const ComponentName = () => {}` vs default export `Wht you have`
2. In your index file, export * from `./ComponentName` - same for other components
3. Where you need to use them `import {ComponentName, other components...} from "./components"`

2024-01-19 21:08 UTC, BukolaF commented on src/components/Hero.jsx
> +           <Link to='loans' className=" md:text-lg mx-20 my-20 sm:text-lg text-lg mt-6 hover:bg-gray-700 mt-10 text-lg bg-blue-950 mx-16 px-6 py-6 text-white flex justify-center items-center">Learn m
https://github.com/BukolaF/loan_website/assets/131551207/6baf90d1-8858-474f-9887-68222f601df7

2024-01-19 21:09 UTC, BukolaF commented on src/components/Footer.jsx
> -               <li className='py-1'>FAQs</li>
it didnt seem like it was needed since there is an about and sign in link at the top of the page

2024-01-21 11:15 UTC, BalogunDell commented on package.json
> +    "sort-by": "^1.2.0",
These are still awaiting answers. If you are not using them, please remove them

2024-01-22 09:29 UTC, BukolaF commented on package.json
> +    "sort-by": "^1.2.0",
They have been removed

2024-01-22 10:35 UTC, BalogunDell requested changes

2024-01-22 10:35 UTC, BalogunDell commented on src/components/index.js
> +import { Hero } from './Hero';
```
import { Footer } from './Footer';
import { Navbar } from './Navbar';
import { NavItems } from './NavItems';
import { Hero } from './Hero';

```

This is not needed again. The exports are just fine

2024-01-22 10:35 UTC, BalogunDell commented on src/pages/index.js
> +export * from './Login'
```
import { About } from './About';
import { Contact } from './Contact';
import { Home } from './Home';
import { Loans } from './Loans';
import { Login } from './Login';

```

this is not needed also. 

Also, you should not be doing any rendering in this file


```

export const index = () => {
  return (
    <div>
        <About />
        <Contact />
        <Home />
        <Loans />
        <Login />
    </div>
  )
}

```

The only thing in this file should be the exports

2024-01-22 10:35 UTC, BalogunDell commented on src/components/.DS_Store
This file should not be pushed

2024-01-22 10:35 UTC, BalogunDell commented on src/.DS_Store
this file should not be here

2024-01-22 10:35 UTC, BalogunDell commented on .DS_Store
this file should not be here also

2024-01-22 16:49 UTC, BalogunDell approved these changes

2024-01-22 16:49 UTC, BalogunDell commented on .gitignore
> +**/.DS_Store
just .DS_Store is enough

2024-01-22 16:49 UTC, BalogunDell commented on .gitignore
> +**/.DS_Store
Please update it in your next PR.

2024-01-22 16:49 UTC, merged