loan and about page
BukolaF/loan_website pull request #4
Opened 2024-01-23 00:50 UTC by BukolaF

this PR:
changes the home page
also includes the loan and about page with changes to the assets folder
the loan page includes the loan-type component

2024-01-23 12:31 UTC, BalogunDell requested changes
Great work! Please address comments

2024-01-23 12:31 UTC, BalogunDell commented on src/components/Footer.jsx
> +    <div className='w-[100%] lg:px-2 mt-2 bg-blue-950 text-gray-300 py-2 px-2'>
Why are we changing the width?

2024-01-23 12:31 UTC, BalogunDell commented on src/components/Footer.jsx
> +        <div className=' container flex flex-row items-center mx-auto md: px-8 py-16 justify-center '>
There's space here md:  what is this meant to do?

2024-01-23 12:31 UTC, BalogunDell commented on src/components/LoanTypes.jsx
> +const lists = [
Please use a more descriptive name

2024-01-23 12:31 UTC, BalogunDell commented on src/components/LoanTypes.jsx
> +          {lists.map((list,) => (
why do we have a comma in this map arguments?

2024-01-23 12:31 UTC, BalogunDell commented on src/components/Navbar.jsx
> +          <div className={!showNav ? 'lg:hidden fixed left-0 top-0 z-[100] w-[70%] h-full overflow-y-auto border-r border-r-blue-800 bg-blue-300 transition-left duration-500 ease left-0' : 'fixed lef
Instead of using ternary operator here. Please use the library called classNames.

2024-01-23 12:31 UTC, BalogunDell commented on src/pages/About.jsx
> +import { Features } from '../components/Features'
This import should be from components.

2024-01-23 12:31 UTC, BalogunDell commented on src/pages/Loans.jsx
> +          <p className='mt-8 text-lg leading-8 text-gray-800'>SecuredLoans has one of the most innovative digital short-term loan products available in Lagos, Nigeria. The process is fast, convenient
```
 <div className=' flex justify-center  text-center mx-auto max-w-7xl px-6 lg:px-8 mt-10'>
        <div className='mx-auto lg:mx-0'>
          <h2 className='text-3xl font-bold tracking-tight pt-10 text-blue-950 sm:text-4xl'> Loan Packages</h2>
          <p className='mt-8 text-lg leading-8 text-gray-800'>SecuredLoans has one of the most innovative digital short-term loan products available in Lagos, Nigeria. The process is fast, convenient, and simple.</p>
        </div>

```
The whole of this can be in its own component

2024-01-23 12:31 UTC, BalogunDell commented on src/pages/Loans.jsx
> +import { LoanTypes } from '../components/LoanTypes'
Same for this, it should come from components directly

2024-01-23 15:22 UTC, BukolaF commented on src/components/LoanTypes.jsx
> +          {lists.map((list,) => (
i will remove it. Its an error

2024-01-26 11:54 UTC, BalogunDell commented on src/App.js
> +        <Route path='/signup' element={<SignUp />} />
Please use route_path

2024-01-26 11:54 UTC, BalogunDell commented on src/components/Features.jsx
> +    {
Please move this to a constant file


```


const featureList = [
    {
      name: 'Seamless and Swift Loans',
      description:
      'Experience the ease of financial support at your fingertips with tailor-made loans just for you',
        icon: GiBanknote,
    },
    {
      name: 'Low Interest Loans',
      description:
        'Experience affordable interest loans without compromising on financial service.',
      icon: GiPayMoney,
    },
    {
      name: 'Smarter Savings',
      description:
        'Discover practical tips and tricks to boost your savings and achieve financial goals.',
      icon: GiPiggyBank,
    },
    {
        name: 'Secured and Save Data',
        description:
          'SecuredLoans takes security extremely seriously and ensure we protect our user data using industry standard encryption.',
        icon: AiOutlineSafety,
      },
  ]
```

2024-01-26 11:54 UTC, BalogunDell commented on src/components/LoanTypes.jsx
> +const lists = [
Also move this to a constant file

2024-01-30 10:52 UTC, BalogunDell requested changes

2024-01-30 10:52 UTC, BalogunDell commented on package.json
> +    "@heroicons/react": "^2.1.1",
Why is this needed when there's react-icons already?

2024-01-30 10:52 UTC, BalogunDell commented on src/components/SignUpform.jsx
> +           validationErrors.password = "password must be at least 8 characters;"
This is a good attempt. I will advise that react-hook-form is used. Makes life much more easier than having to write this lengthy validation. https://www.npmjs.com/package/react-hook-form

2024-01-30 10:52 UTC, BalogunDell commented on src/components/SignUpform.jsx
> +            console.log(result.data)
No console log is allowed please

2024-01-30 10:52 UTC, BalogunDell commented on src/components/SignUpform.jsx
> +            <input className='w-full px-3 py-2 border rounded-lg bg-gray-300 focus:border-gray-500'  name='fname' onChange={(e)=> setSignUpData({...signUpData, fname: e.target.value})} placeholder='S
Please what is fname? Kindly use descriptive names

2024-01-30 10:52 UTC, BalogunDell commented on src/components/SignUpform.jsx
> +            <input className='w-full px-3 py-2 border rounded-lg bg-gray-300 focus:border-gray-500' name='password' onChange={(e)=> setSignUpData({...signUpData, password: e.target.value})} placehold
cpassword is not a valid name, Kindly use descriptive names

2024-01-30 10:52 UTC, BalogunDell commented on src/components/index.js
> +export * from '../constant/LoanTypes';
evertyhting should be imported from constant

```
export * from '../constant/Features';
export * from '../constant/LoanTypes';
```

should be 

```
export * from '../constant/';
```

2024-01-30 10:52 UTC, BalogunDell commented on src/constant/LoanTypes.jsx
> +import personal_image_logo from '../components/Assets/personal_image_logo.jpeg';
We should not have assets inside components. Assets should be a standalone folder outside the components folder

2024-01-30 10:52 UTC, BalogunDell commented on src/pages/Login.jsx
> +    } else if(/^[A-Za-z]\._-[0-9]*[@][A-Za-z]*[.][a-z]{2,4}$/.test(loginData.email)){
use react-hook-form

2024-01-30 10:52 UTC, BalogunDell commented on src/pages/Login.jsx
> +                result.data.map(user => {
Please use [async and await ](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/async_function)

2024-01-30 10:52 UTC, BalogunDell commented on src/pages/UserDashboard.jsx
> +    <>
Do you need <> ? There's already a wrapper for all the children tags

2024-01-31 18:02 UTC, BalogunDell requested changes

2024-01-31 18:02 UTC, BalogunDell commented on src/components/SignUpform.jsx
> +          .then(response=>{
Sweeet. You don't need a .then when using async await

2024-01-31 18:02 UTC, BalogunDell commented on src/pages/Login.jsx
> +            .then(response =>{
Same here

2024-01-31 18:02 UTC, BalogunDell commented on src/pages/Login.jsx
> +                    // }
No commented code please.

2024-01-31 18:02 UTC, BalogunDell commented on src/pages/UserDashboard.jsx
> +      {menu.map(({path,link}) => <li key={link} className='p-8 font-extrabold text-white' >
No commented code please

2024-02-01 18:06 UTC, BalogunDell requested changes

2024-02-01 18:06 UTC, BalogunDell commented on src/components/SignUpform.jsx
> +              register('')
There's a possibility that this errors out, please wrap it in try catch block and handle the error

2024-02-02 16:12 UTC, BalogunDell requested changes

2024-02-02 16:12 UTC, BalogunDell commented on src/components/SignUpform.jsx
> +            console.log(data);
Please no console log

Why are we using finally?

2024-02-02 16:12 UTC, BalogunDell commented on src/pages/Login.jsx
> +            console.log(data);
Same here too with the previous comment

2024-02-05 14:24 UTC, BalogunDell requested changes

2024-02-05 14:24 UTC, BalogunDell commented on src/App.js
> +import { UserDashboardMenu } from './components/UserDashboardMenu';
These should come from pages and components respectively

```

import {LoanApplications, LoanHistory, UserProfile, NewUserForm} from './userpages/'
import { UserDashboardMenu } from './components/UserDashboardMenu';
```

2024-02-05 14:24 UTC, BalogunDell commented on src/App.js
> +   <Route path='/newform' element={<NewUserForm  />} />
This route is not a valid path name and you should use the ROUTE_PATH constant

2024-02-05 14:24 UTC, BalogunDell commented on src/App.js
> +   <Route path='/newform' element={<NewUserForm  />} />
This route is not a valid path name and you should use the ROUTE_PATH constant

2024-02-05 14:24 UTC, BalogunDell commented on src/components/UserDashboardMenu.jsx
> +}
This file has very similar content to what's in src/components/AdminDashboardMenu.jsx

Please clean this up with reusable component

2024-02-05 14:24 UTC, BalogunDell commented on src/constant/LoanHistoryData.jsx
> +import React from 'react';
This is a constant file. You should not have jsx in this file.

2024-02-05 14:24 UTC, BalogunDell commented on src/constant/LoanStatus.jsx
> +    <h1 className='capitalize py-2 px-6 rounded-md font-bold bg-orange-600 text-orange-200'>
This is not a constant. It should be in an util or a seperate jsx file

2024-02-05 14:24 UTC, BalogunDell commented on src/constant/index.js
> +
Everything should be exported from a constant barrel (index) file

2024-02-05 14:24 UTC, BalogunDell commented on src/pages/Login.jsx
> +        if (user.email === data.email || user.password === data.password || data.role === 'Admin'){
Do not hard code `Admin`, please move it to a constant. const ADMIN = 'Admin'

2024-02-05 14:24 UTC, BalogunDell commented on src/pages/Login.jsx
> +         } else if (user.email === data.email || user.password === data.password || data.role === 'Registered User'){
Same as this 'Registered User' - Why are u using registered user here?

2024-02-05 14:24 UTC, BalogunDell commented on src/pages/UserDashboard.jsx
> +import { UserDashboardMenu } from '../components/UserDashboardMenu';
Import from components

2024-02-05 23:25 UTC, BukolaF commented on src/constant/index.js
> +
it gives an error message
![Image 06-02-2024 at 00 24](https://github.com/BukolaF/loan_website/assets/131551207/6f90fdac-3b85-4ccb-b2de-b730962d1855)

2024-02-05 23:26 UTC, BukolaF commented on src/pages/Login.jsx
> +         } else if (user.email === data.email || user.password === data.password || data.role === 'Registered User'){
> Same as this 'Registered User' - Why are u using registered user here?

i think they are different because, it wasnt navigating to the registered user page until i changed it

2024-02-06 09:22 UTC, BalogunDell commented on src/constant/index.js
> +
This is because it was not exported the right way. Your index file should export each of the files within the components

2024-02-06 09:24 UTC, BalogunDell commented on src/pages/Login.jsx
> +         } else if (user.email === data.email || user.password === data.password || data.role === 'Registered User'){
I don't understand pleas. This code does not look new. It's a new code so I don't get what you mean by you changing it. Also, if only works when you use `Registered User`, then something is wrong somewhere. Kindly look into this

2024-02-06 21:48 UTC, BukolaF commented on src/App.js
> +   <Route path='/newform' element={<NewUserForm  />} />
![Image 06-02-2024 at 22 46](https://github.com/BukolaF/loan_website/assets/131551207/9d0fb89f-5113-471a-bdeb-eacb36d38723)
![Image 06-02-2024 at 22 42](https://github.com/BukolaF/loan_website/assets/131551207/8a84c3ee-f769-4539-8bb0-e9bf1113d5af)
i dont know what is wrong with the route paths here

2024-02-29 08:11 UTC, merged